import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-blue-300 py-4">
          <nav className=" flex container  justify-between items-center">
            <Link href={"/"}>Home</Link>
            <div className="flex gap-10">
              <Link href={"/dashboard"}>Dashboard</Link>
              <Link href={"/register"}>Register</Link>
            </div>
          </nav>
        </header>
        <main> {children}</main>
      </body>
    </html>
  );
}
